-- VHDL Entity alien_game_lib.c1_b2_decrementer.symbol
--
-- Created:
--          by - Jani Koistinen.UNKNOWN (DESKTOP-J0NR04D)
--          at - 14:54:15 23/09/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_b2_decrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_b2_decrementer ;

--
-- VHDL Architecture alien_game_lib.c1_b2_decrementer.struct
--
-- Created:
--          by - Jani Koistinen.UNKNOWN (DESKTOP-J0NR04D)
--          at - 15:25:26 23/09/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_b2_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL sw0    : std_logic;
   SIGNAL sw1    : std_logic;


   -- Component Declarations
   COMPONENT c1_full_adder
   PORT (
      carry_in : IN     std_logic ;
      sw0      : IN     std_logic ;
      sw1      : IN     std_logic ;
      carry    : OUT    std_logic ;
      sum      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_full_adder USE ENTITY alien_game_lib.c1_full_adder;
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   sw0 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   sw1 <= '1';

   -- Instance port mappings.
   U_1 : c1_full_adder
      PORT MAP (
         carry_in => carry,
         sw0      => sw0,
         sw1      => value(1),
         carry    => carry1,
         sum      => result(1)
      );
   U_2 : c1_full_adder
      PORT MAP (
         carry_in => carry1,
         sw0      => sw1,
         sw1      => value(2),
         carry    => OPEN,
         sum      => result(2)
      );
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout,
         sw1   => value(0),
         carry => carry,
         sum   => result(0)
      );

END struct;
