-- VHDL Entity alien_game_lib.c1_full_adder.symbol
--
-- Created:
--          by - Jani Koistinen.UNKNOWN (DESKTOP-J0NR04D)
--          at - 15:18:13 23/09/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_full_adder IS
   PORT( 
      carry_in : IN     std_logic;
      sw0      : IN     std_logic;
      sw1      : IN     std_logic;
      carry    : OUT    std_logic;
      sum      : OUT    std_logic
   );

-- Declarations

END c1_full_adder ;

--
-- VHDL Architecture alien_game_lib.c1_full_adder.struct
--
-- Created:
--          by - Jani Koistinen.UNKNOWN (DESKTOP-J0NR04D)
--          at - 15:18:13 23/09/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_full_adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic;
   SIGNAL din1 : std_logic;
   SIGNAL sw2  : std_logic;


   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   carry <= din0 OR din1;

   -- Instance port mappings.
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => sw0,
         sw1   => sw1,
         carry => din1,
         sum   => sw2
      );
   U_1 : c1_t1_half_adder
      PORT MAP (
         sw0   => carry_in,
         sw1   => sw2,
         carry => din0,
         sum   => sum
      );

END struct;
