-- VHDL Entity alien_game_lib.c2_t1_hello_led.symbol
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-304-SPC)
--          at - 14:33:35 22.09.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_hello_led IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_hello_led ;

--
-- VHDL Architecture alien_game_lib.c2_t1_hello_led.struct
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-304-SPC)
--          at - 15:40:24 22.09.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din1 : std_logic_vector(23 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   x_coord <= "00001000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   y_coord <= "00001000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   din0 <= x"0000FF";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   din1 <= x"00FF00";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(din0, din1, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => color_BGR <= din0;
      WHEN '1' => color_BGR <= din1;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- Instance port mappings.

END struct;
