-- VHDL Entity alien_game_lib.c2_t1_hello_led_static.symbol
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-304-SPC)
--          at - 14:59:30 22.09.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_hello_led_static IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_hello_led_static ;

--
-- VHDL Architecture alien_game_lib.c2_t1_hello_led_static.struct
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-304-SPC)
--          at - 15:39:28 22.09.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_hello_led_static IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   color_BGR <= x"FF0000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   x_coord <= "00001000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   y_coord <= "00001000";

   -- Instance port mappings.

END struct;
