-- VHDL Entity alien_game_lib.c3_direction_block.symbol
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-310-SPC)
--          at - 12:57:12 29.09.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_direction_block IS
   PORT( 
      clk       : IN     std_logic;
      rst_n     : IN     std_logic;
      x_coord_0 : IN     std_logic;
      x_coord_7 : IN     std_logic;
      direction : OUT    std_logic
   );

-- Declarations

END c3_direction_block ;

--
-- VHDL Architecture alien_game_lib.c3_direction_block.struct
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-304-SPC)
--          at - 12:27:20 13.10.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_direction_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL direction_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   direction_internal <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= dout1;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(direction_internal, x_coord_7, dout)
   BEGIN
      CASE dout IS
      WHEN '0' => dout1 <= direction_internal;
      WHEN '1' => dout1 <= x_coord_7;
      WHEN OTHERS => dout1 <= 'X';
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   dout <= x_coord_0 OR x_coord_7;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   direction <= direction_internal;

END struct;
