-- VHDL Entity alien_game_lib.c4_b1_bullet_flight_modeling.symbol
--
-- Created:
--          by - PAMPPU.UNKNOWN (DESKTOP-3NB66EQ)
--          at - 19:23:38 30/11/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_b1_bullet_flight_modeling IS
   PORT( 
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      gun_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      rst_n       : IN     std_logic;
      bullet_BGR  : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x    : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_b1_bullet_flight_modeling ;

--
-- VHDL Architecture alien_game_lib.c4_b1_bullet_flight_modeling.fsm
--
-- Created:
--          by - PAMPPU.UNKNOWN (DESKTOP-3NB66EQ)
--          at - 19:23:38 30/11/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c4_b1_bullet_flight_modeling IS

   TYPE STATE_TYPE IS (
      init,
      bullet_flight
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= init;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      btn,
      bullet_y,
      current_state,
      enable
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN init => 
            IF (btn = '1') THEN 
               next_state <= bullet_flight;
            ELSE
               next_state <= init;
            END IF;
         WHEN bullet_flight => 
            IF (enable = '1') THEN 
               IF (bullet_y > "00000001") THEN 
                  next_state <= bullet_flight;
               ELSE
                  IF (bullet_y = "00000001") THEN 
                     next_state <= init;
                  END IF;
               END IF;
            ELSE
               next_state <= bullet_flight;
            END IF;
         WHEN OTHERS =>
            next_state <= init;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      btn,
      bullet_x,
      bullet_y,
      current_state,
      enable,
      gun_x_coord
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      bullet_BGR <= x"FF0000";
      bullet_x <= "00000000";
      bullet_y <= "00000000";

      -- Combined Actions
      CASE current_state IS
         WHEN init => 
            IF (btn = '1') THEN 
               bullet_x <= gun_x_coord;
               bullet_y <= "01000000";
            END IF;
         WHEN bullet_flight => 
            IF (enable = '1') THEN 
               bullet_x <= bullet_x;
               bullet_y <= (bullet_y - "00000001");
            END IF;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
