-- VHDL Entity alien_game_lib.c4_t1_pixel_indexer.symbol
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-320-SPC)
--          at - 14:03:49  3.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_pixel_indexer IS
   PORT( 
      gun_pix_id : IN     std_logic_vector (1 DOWNTO 0);
      x_in       : IN     std_logic_vector (7 DOWNTO 0);
      y_in       : IN     std_logic_vector (7 DOWNTO 0);
      x_out      : OUT    std_logic_vector (7 DOWNTO 0);
      y_out      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_pixel_indexer ;

--
-- VHDL Architecture alien_game_lib.c4_t1_pixel_indexer.struct
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-320-SPC)
--          at - 14:03:49  3.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_pixel_indexer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din3  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'fixshift'
   SIGNAL mw_U_0temp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'fixshift'
   SIGNAL mw_U_1temp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'fixshift'
   SIGNAL mw_U_2temp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'fixshift'
   dout <= mw_U_0temp_dout;
   u_0combo_proc: PROCESS (x_in)
   BEGIN
      mw_U_0temp_dout <= (OTHERS => '0');
      mw_U_0temp_dout(7 DOWNTO 1) <= x_in(6 + 0 DOWNTO 0);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'fixshift'
   din3 <= mw_U_1temp_dout;
   u_1combo_proc: PROCESS (x_in)
   BEGIN
      mw_U_1temp_dout <= (OTHERS => '0');
      mw_U_1temp_dout(6 DOWNTO 0) <= x_in(7 + 0 DOWNTO 1 + 0);
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'fixshift'
   dout1 <= mw_U_2temp_dout;
   u_2combo_proc: PROCESS (y_in)
   BEGIN
      mw_U_2temp_dout <= (OTHERS => '0');
      mw_U_2temp_dout(6 DOWNTO 0) <= y_in(7 + 0 DOWNTO 1 + 0);
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'mux'
   u_8combo_proc: PROCESS(y_in, dout1, gun_pix_id)
   BEGIN
      CASE gun_pix_id IS
      WHEN "00" => y_out <= y_in;
      WHEN "01" => y_out <= dout1;
      WHEN "10" => y_out <= y_in;
      WHEN "11" => y_out <= y_in;
      WHEN OTHERS => y_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'mux'
   u_10combo_proc: PROCESS(x_in, dout, din3, gun_pix_id)
   BEGIN
      CASE gun_pix_id IS
      WHEN "00" => x_out <= x_in;
      WHEN "01" => x_out <= x_in;
      WHEN "10" => x_out <= dout;
      WHEN "11" => x_out <= din3;
      WHEN OTHERS => x_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_10combo_proc;

   -- Instance port mappings.

END struct;
