-- VHDL Entity alien_game_lib.c5_t2_TOP_LEVEL.symbol
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-311-SPC)
--          at - 13:34:13 17.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t2_TOP_LEVEL IS
   PORT( 
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      channel : OUT    std_logic_vector (7 DOWNTO 0);
      lat     : OUT    std_logic;
      s_clk   : OUT    std_logic;
      s_rst   : OUT    std_logic;
      s_sda   : OUT    std_logic;
      sb      : OUT    std_logic
   );

-- Declarations

END c5_t2_TOP_LEVEL ;

--
-- VHDL Architecture alien_game_lib.c5_t2_TOP_LEVEL.struct
--
-- Created:
--          by - koistin3.UNKNOWN (HTC219-311-SPC)
--          at - 13:34:13 17.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY pre_made;

ARCHITECTURE struct OF c5_t2_TOP_LEVEL IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color_BGR  : std_logic_vector(23 DOWNTO 0);
   SIGNAL frame_done : std_logic;
   SIGNAL w_rdy      : std_logic;
   SIGNAL write      : std_logic;
   SIGNAL x_coord    : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord    : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c5_t2_game_top_level
   PORT (
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic ;
      rst_n       : IN     std_logic ;
      write_ready : IN     std_logic ;
      color_BGR   : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done  : OUT    std_logic ;
      write       : OUT    std_logic ;
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT display_controller
   PORT (
      clk        : IN     std_logic ;
      color_BGR  : IN     std_logic_vector (23 DOWNTO 0);
      frame_done : IN     std_logic ;
      rst_n      : IN     std_logic ;
      write      : IN     std_logic ;
      x_coord    : IN     std_logic_vector (7 DOWNTO 0);
      y_coord    : IN     std_logic_vector (7 DOWNTO 0);
      channel    : OUT    std_logic_vector (7 DOWNTO 0);
      lat        : OUT    std_logic ;
      s_clk      : OUT    std_logic ;
      s_rst      : OUT    std_logic ;
      s_sda      : OUT    std_logic ;
      sb         : OUT    std_logic ;
      w_rdy      : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c5_t2_game_top_level USE ENTITY alien_game_lib.c5_t2_game_top_level;
   FOR ALL : display_controller USE ENTITY pre_made.display_controller;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : c5_t2_game_top_level
      PORT MAP (
         btn         => btn,
         clk         => clk,
         rst_n       => rst_n,
         write_ready => w_rdy,
         color_BGR   => color_BGR,
         frame_done  => frame_done,
         write       => write,
         x_coord     => x_coord,
         y_coord     => y_coord
      );
   U_1 : display_controller
      PORT MAP (
         clk        => clk,
         color_BGR  => color_BGR,
         frame_done => frame_done,
         rst_n      => rst_n,
         write      => write,
         x_coord    => x_coord,
         y_coord    => y_coord,
         channel    => channel,
         lat        => lat,
         s_clk      => s_clk,
         s_rst      => s_rst,
         s_sda      => s_sda,
         sb         => sb,
         w_rdy      => w_rdy
      );

END struct;
