-- VHDL Entity alien_game_lib.c6_t1_hit_detector.symbol
--
-- Created:
--          by - sgjele.UNKNOWN (HTC219-313-SPC)
--          at - 12:52:22 24.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t1_hit_detector IS
   PORT( 
      Alien_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      Gun_x_coord   : IN     std_logic_vector (7 DOWNTO 0);
      button        : IN     std_logic;
      clk           : IN     std_logic;
      rst_n         : IN     std_logic;
      hit           : OUT    std_logic
   );

-- Declarations

END c6_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c6_t1_hit_detector.struct
--
-- Created:
--          by - sgjele.UNKNOWN (HTC219-317-SPC)
--          at - 13:53:33 30.11.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c6_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL q     : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   din0 <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_7reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_7reg_cval <= button;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'sand'
   dout1 <= button AND q;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'sand'
   u_1combo_proc: PROCESS(Gun_x_coord, Alien_x_coord)
   VARIABLE temp_dout : std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_dout := Gun_x_coord AND Alien_x_coord;
      q <=  temp_dout(0);
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'sand'
   hit <= dout2 AND din0;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'sxor'
   dout2 <= din0 XOR dout1;

   -- Instance port mappings.

END struct;
